# pytorch_lightning==2.0.9
seed_everything: 0


custom:
  project_name: sr_indie_rnn_PHD-77
  use_wandb: true
  experiment_name: peavey_6505
  name: 6505_fir3_naiveinit

trainer:
  accelerator: cpu
  max_epochs: 250
  log_every_n_steps: 1
  enable_checkpointing: true
  check_val_every_n_epoch: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        monitor: val_loss
        save_last: true
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 40
        min_delta: 1e-3
        monitor: val_loss
        stopping_threshold: 1e-4

model:
  class_path: sr_indie_rnn.sr_indie_train.FIRInterpRNN
  init_args:

    sample_rate: 44100
    base_sample_rate: 44100
    learning_rate: 1e-4
    tbptt_steps: 2000

    rnn_model_json: 'Proteus_Tone_Packs/6505Plus_Red_DirectOut.json'
    order: 3
    loss_module:
      class_path: utils.loss_modules.TimeDomainLoss


data:
  class_path: utils.dataset.RNNDataModule
  init_args:
    train_sequence_length_seconds: 1.0
    val_sequence_length_seconds: 10.0
    test_sequence_length_seconds: 10.0
    batch_size: 10
    device_name: '6505Plus_Red_DirectOut'
    base_path: '../../audio_datasets/dist_fx_192k/44k/'
    orig_sr: 147
    new_sr: 160




