# pytorch_lightning==2.0.9
seed_everything: 0


custom:
  project_name: rn_indie_rnn
  use_wandb: false
  experiment_name: muff
  name: muff_wavenet_1_10_16_3

trainer:
  accelerator: cpu
  max_epochs: 1000
  log_every_n_steps: 1
  enable_checkpointing: true
  check_val_every_n_epoch: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        monitor: val_loss
        save_last: true
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 100
        min_delta: 1e-3
        monitor: val_loss

model:
  class_path: sr_indie_rnn.sr_indie_train.BaselineCNN
  init_args:
    sample_rate: 44100
    learning_rate: 5e-4

    model:
      class_path: sr_indie_rnn.modules.GCNNet

    loss_module:
      class_path: utils.loss_modules.TimeDomainLoss


data:
  class_path: utils.dataset.RNNDataModule
  init_args:
    train_sequence_length_seconds: 1.0
    val_sequence_length_seconds: 5.0
    test_sequence_length_seconds: 5.0
    batch_size: 16
    base_path: '../../audio_datasets/dist_fx/'
    train_input: 'train/muff-input.wav'
    train_target: 'train/muff-target.wav'
    val_input: 'val/muff-input.wav'
    val_target: 'val/muff-target.wav'
    test_input: 'test/muff-input.wav'
    test_target: 'test/muff-target.wav'




