# pytorch_lightning==2.0.9
seed_everything: 0


custom:
  project_name: rn_indie_rnn
  use_wandb: true
  experiment_name: dyno
  name: diodeclipper_dyno8

trainer:
  accelerator: cpu
  max_epochs: 500
  log_every_n_steps: 1
  enable_checkpointing: true
  check_val_every_n_epoch: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        monitor: val_loss
        save_last: true
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 40
        min_delta: 1e-3
        monitor: val_loss
        stopping_threshold: 1e-4

model:
  class_path: sr_indie_rnn.sr_indie_train.BaselineRNN
  init_args:
    sample_rate: 44100
    learning_rate: 5e-4
    tbptt_steps: 2048

    rnn_model:
      class_path: sr_indie_rnn.modules.RNN
      init_args:
        cell_type: 'dyno'
        hidden_size: 8
        residual_connection: true
        num_layers: 1

    loss_module:
      class_path: utils.loss_modules.TimeDomainLoss


data:
  class_path: utils.dataset.RNNDataModule
  init_args:
    train_sequence_length_seconds: 1.0
    val_sequence_length_seconds: 5.0
    test_sequence_length_seconds: 5.0
    batch_size: 16
    train_input: 'dist_fx/train/diodeclipper-input.wav'
    train_target: 'dist_fx/train/diodeclipper-gain5-target.wav'
    val_input: 'dist_fx/val/diodeclipper-input.wav'
    val_target: 'dist_fx/val/diodeclipper-gain5-target.wav'
    test_input: 'dist_fx/test/diodeclipper-input.wav'
    test_target: 'dist_fx/test/diodeclipper-gain5-target.wav'
    base_path: '/disk/scratch1/s1409071/audio_datasets/'






