# pytorch_lightning==2.0.9
seed_everything: 0


custom:
  project_name: jax_rnn
  use_wandb: true
  experiment_name: 'gypsy'
  name: 'pytorch'

trainer:
  accelerator: gpu
  max_epochs: 50
  log_every_n_steps: 1
  enable_checkpointing: true
  check_val_every_n_epoch: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        monitor: val_loss
        save_last: true
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 40
        min_delta: 1e-3
        monitor: val_loss
        stopping_threshold: 1e-4

model:
  class_path: sr_indie_rnn.sr_indie_train.BaselineRNN
  init_args:
    sample_rate: 44100
    learning_rate: 1e-3
    tbptt_steps: 4410

    rnn_model:
      class_path: sr_indie_rnn.modules.AudioRNN
      init_args:
        cell_type: 'lstm'
        hidden_size: 32
        residual_connection: true

    loss_module:
      class_path: utils.loss_modules.TimeDomainLoss


data:
  class_path: utils.dataset.RNNDataModule
  init_args:
    train_sequence_length_seconds: 1.0
    val_sequence_length_seconds: 10.0
    test_sequence_length_seconds: 10.0
    batch_size: 10
    device_name: 'gypsy'
    base_path: '../../audio_datasets/dist_fx_192k/44k/'




