# pytorch_lightning==2.0.9
seed_everything: 0


custom:
  project_name: rn_indie_rnn
  use_wandb: true
  experiment_name: starleader
  name: gru_16_88k

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 500
  log_every_n_steps: 1
  enable_checkpointing: true
  check_val_every_n_epoch: 10

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        monitor: val_loss
        save_last: true
#    - class_path: pytorch_lightning.callbacks.EarlyStopping
#      init_args:
#        patience: 200
#        min_delta: 1e-4
#        monitor: val_loss_esr
#        stopping_threshold: 1e-4

model:
  class_path: sr_indie_rnn.sr_indie_train.BaselineRNN
  init_args:
    sample_rate: 88200
    learning_rate: 5e-4
    tbptt_steps: 2048

    rnn_model:
      class_path: sr_indie_rnn.modules.RNN
      init_args:
        cell_type: 'gru'
        hidden_size: 16
        residual_connection: true

    loss_module:
      class_path: utils.loss_modules.TimeDomainLoss


data:
  class_path: utils.dataset.RNNDataModule
  init_args:
    train_sequence_length_seconds: 1.0
    val_sequence_length_seconds: 5.0
    test_sequence_length_seconds: 5.0
    batch_size: 16
    train_input: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/train/muff-input.wav'
    train_target: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/train/muff-target.wav'
    val_input: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/val/muff-input.wav'
    val_target: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/val/muff-target.wav'
    test_input: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/test/muff-input.wav'
    test_target: '/disk/scratch1/s1409071/audio_datasets/dist_fx/88kHz/test/muff-target.wav'




